name: Release to GitHub Pages

on:
  push:
    tags:
      - 'v*'   # Only run when a version tag is pushed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repo at tag
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history for commit hash

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify version consistency
        run: |
          echo "Verifying version consistency..."
          echo "Package.json version: $(node -p "require('./package.json').version")"
          echo "Git tag: ${{ github.ref_name }}"
          
          # Extract version from tag (remove 'v' prefix)
          TAG_VERSION="${{ github.ref_name }}"
          TAG_VERSION=${TAG_VERSION#v}
          
          # Check if package.json version matches tag
          PKG_VERSION=$(node -p "require('./package.json').version")
          if [ "$PKG_VERSION" != "$TAG_VERSION" ]; then
            echo "❌ Version mismatch: package.json ($PKG_VERSION) != tag ($TAG_VERSION)"
            exit 1
          fi
          echo "✅ Version consistency verified"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## What's Changed
            
            This release includes all changes since the last version tag.
            
            ### Version Information
            - **Version**: ${{ github.ref_name }}
            - **Commit**: ${{ github.sha }}
            - **Deployed**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
            
            ### Deployment
            This version has been automatically deployed to GitHub Pages.
            
            ---
            
            For detailed changelog, see [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md).
          draft: false
          prerelease: false
