name: Versioning Pipeline Diagnostics

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      run_diagnostics:
        description: 'Run full versioning diagnostics'
        required: false
        default: true
        type: boolean

jobs:
  versioning-diagnostics:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for git diagnostics
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    
    - name: Run versioning diagnostics
      run: npm run test:versioning
      continue-on-error: true
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: versioning-diagnostics-results
        path: |
          tests/test-results/
          tests/playwright-report/
        retention-days: 30
    
    - name: Comment on PR with diagnostics
      if: github.event_name == 'pull_request' && always()
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // Read test results if available
          let diagnosticsInfo = '## 🔍 Versioning Pipeline Diagnostics\n\n';
          
          try {
            const resultsPath = path.join(process.cwd(), 'tests', 'test-results', 'versioning-results.json');
            if (fs.existsSync(resultsPath)) {
              const results = JSON.parse(fs.readFileSync(resultsPath, 'utf8'));
              diagnosticsInfo += `**Test Results:** ${results.stats.passed} passed, ${results.stats.failed} failed\n\n`;
              
              if (results.stats.failed > 0) {
                diagnosticsInfo += '❌ **Versioning issues detected!** Please check the test results.\n\n';
              } else {
                diagnosticsInfo += '✅ **Versioning pipeline is healthy!**\n\n';
              }
            }
          } catch (error) {
            diagnosticsInfo += '⚠️ **Could not read test results**\n\n';
          }
          
          diagnosticsInfo += 'Run `npm run version:diagnose` locally to debug versioning issues.\n\n';
          diagnosticsInfo += '**Available diagnostic commands:**\n';
          diagnosticsInfo += '- `npm run test:versioning` - Run all diagnostics\n';
          diagnosticsInfo += '- `npm run test:versioning:debug` - Debug mode\n';
          diagnosticsInfo += '- `npm run test:versioning:ui` - Interactive UI\n';
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: diagnosticsInfo
          });

  post-release-validation:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: versioning-diagnostics
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    
    - name: Wait for deployment
      run: |
        echo "Waiting for GitHub Pages deployment..."
        sleep 60
    
    - name: Validate deployment
      run: npm run test:versioning
      continue-on-error: true
    
    - name: Create deployment status
      if: always()
      uses: actions/github-script@v7
      with:
        script: |
          const tag = context.ref.replace('refs/tags/', '');
          const status = '${{ job.status }}' === 'success' ? 'success' : 'failure';
          
          github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: status,
            target_url: `${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`,
            description: status === 'success' ? 
              `Versioning diagnostics passed for ${tag}` : 
              `Versioning diagnostics failed for ${tag}`,
            context: 'versioning-diagnostics'
          });
